default_stages: [commit, push]
fail_fast: true # stop running hooks at the first failure
minimum_pre_commit_version: 2.15.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: git-check # check for git conflict markers and whitespace errors - uses git internally

-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-imports
    -   id: golangci-lint
        args: [--timeout=5m]
    -   id: go-unit-tests
    -   id: go-build
    -   id: go-mod-tidy
