server:
  rest_port: 8080
  shutdown_timeout: 30s

database:
  host: localhost
  port: 5432
  user: example
  password: change-me
  dbname: sil_backend_assessment_db
  sslmode: disable

redis:
  address: localhost:6379
  password: change-me
  db: 0

auth:
  jwt_secret: change-me
  jwt_expiry: 6h
  jwt_refresh_secret: change-me
  jwt_refresh_expiry: 24h

smtp:
  host: smtp.example.com
  port: 587
  username: example@example.com
  password: change-me
  from: example@example.com
  tls: true

at:
  api_key: change-me
  username: example@example.com

oidc:
  enabled: false
  provider_url: https://accounts.google.com
  client_id: your-google-client-id
  client_secret: your-google-client-secret
  redirect_url: http://localhost:8080/auth/oidc/callback
  scopes:
    - openid
    - profile
    - email

logging:
  level: info
  file: sil-backend-assessment.log

metrics:
  enabled: true
  port: 9090
  path: /metrics

migrations:
  dir: cmd/migrate/migrations
  config_dir: ./config


