apiVersion: apps/v1
kind: Deployment
metadata:
  name: sil-backend-assessment
  namespace: sil-backend-assessment
  labels:
    app: sil-backend-assessment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sil-backend-assessment
  template:
    metadata:
      labels:
        app: sil-backend-assessment
    spec:
      initContainers:
      - name: migrate
        image: sil-backend-assessment:latest
        command: ["./migrate", "up"]
        env:
        - name: CONFIG_FILE
          value: /app/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      containers:
      - name: sil-backend-assessment
        image: sil-backend-assessment:latest
        command: ["./server", "-config", "/app/config/config.yaml"]
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: CONFIG_FILE
          value: /app/config/config.yaml
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sil-backend-secrets
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: sil-backend-secrets
              key: jwt-refresh-secret
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sil-backend-secrets
              key: smtp-password
        - name: AT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sil-backend-secrets
              key: at-api-key
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: sil-backend-secrets
              key: oidc-client-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sil-backend-secrets
              key: db-password
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: sil-backend-config
      - name: secrets
        secret:
          secretName: sil-backend-secrets
