apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sil-backend-assessment

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- redis.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

images:
- name: sil-backend-assessment
  newTag: latest

commonLabels:
  app: sil-backend-assessment
  version: v1.0.0
  environment: development
